<?php
/**
 * @file
 * Code for the Basic Page Feature.
 */

include_once 'basic_page_feature.features.inc';

/**
 * Implements hook_integration().
 */
function basic_page_feature_integration() {
  // Add links to views if a module wants to do that.
  return array(
    'groups_feature' => array(
      'entity' => array(
        'node'=> array(
          'basic_page' => array(
            'add_content_link' => TRUE,
          ),
        ),
      ),
    ),
  );
}
